### ISSUE TITLE
False positive in Universal.CodeAnalysis.ConstructorDestructorReturn

### ISSUE THREAD

**Issue by anomiex** [PHPCSStandards/PHPCSExtra#201]
## Bug Description

The sniff `Universal.CodeAnalysis.ConstructorDestructorReturn` false-positives if an anonymous function is used inside a constructor. Presumably this also happens for destructors.

## Given the following reproduction Scenario

The issue happens when running this command:

```bash
vendor/bin/phpcs -s --standard=Universal --sniffs=Universal.CodeAnalysis.ConstructorDestructorReturn test.php
```

... over a file containing this code:
```php
<?php

class Foo {
    public function __construct() {
        do_something(
            function () {
                return true;
            },
        );

        $this->callback = function () {
            return false;
        };
    }
}
```

### I'd expect the following behaviour

No warnings or errors.

### Instead this happened

```
FILE: /tmp/test/test.php
--------------------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 0 ERRORS AND 2 WARNINGS AFFECTING 2 LINES
--------------------------------------------------------------------------------------------------------------------------------------------------------------------
  7 | WARNING | A "__construct()" magic method can not return a value. Found: "return true;"
    |         | (Universal.CodeAnalysis.ConstructorDestructorReturn.ReturnValueFound)
 12 | WARNING | A "__construct()" magic method can not return a value. Found: "return false;"
    |         | (Universal.CodeAnalysis.ConstructorDestructorReturn.ReturnValueFound)
--------------------------------------------------------------------------------------------------------------------------------------------------------------------
```

## Environment

| Environment              | Answer
| ------------------------ | -------
| PHP version              | 8.0.26
| PHP_CodeSniffer version  | 3.7.1
| PHPCSExtra version       | 1.0.0
| PHPCSUtils version       | 1.0.0
| Install type             | Composer project local

## Tested Against `develop` branch?
- [x] I have verified the issue still exists in the `develop` branch of PHPCSExtra.

**Comment by jrfnl** [comment]
@anomiex Thanks for reporting this! I have confirmed the bug. Fix upcoming.

**Comment by jrfnl** [comment]
PR #202 should fix the issue.

**Comment by anomiex** [comment]
Thanks!
