### ISSUE TITLE
Rename default branch from master to main

### ISSUE THREAD

**Issue by theresenabl** [PHPCSStandards/PHPCSExtra#60]
Information on why we should do that and how you can do that is available: https://www.hanselman.com/blog/EasilyRenameYourGitDefaultBranchFromMasterToMain.aspx

**Comment by jrfnl** [comment]
The default branch is `develop`.

Though I get what you mean and this is already in the works and will be fixed with the next release, though the WIP is based on naming it `stable` to contrast with `develop`.

**Comment by theresenabl** [comment]
Gr8, I still suggest `main` because Github will do the same; completion after `tab` works

**Comment by jrfnl** [comment]
@theresenabl I presume you mean `git` not GitHub ? Or is GH planning to change the default branch name for new repos ? If so: link please ;-)

What's the advantage to that though ? Contributors would never work on that branch, they need `develop` to base their feature branches off and other than that, I expect people to use Composer, so I can't think of a use case where people would need the autocompletion ?

**Comment by theresenabl** [comment]
Github. Tweet from CEO: https://twitter.com/natfriedman/status/1271253144442253312

**Comment by jrfnl** [comment]
Interesting. Thanks for the link. I do see various options being discussed in the thread, including GH changing their own repos to `trunk` and `main` having other slavery related connotations, so I'm still not convinced that `main` is the best choice.

**Comment by kadamwhite** [comment]
WordPress as a project is moving towards using `trunk` as their default branch name, for better parity with that project's SVN roots—not all projects need to use the same naming scheme. So long as we're successfully avoiding names like `master` with problematic legacies, I'd argue that we don't need to worry about standardizing on one branch name across the entire internet. (And if we did, the `git` project itself would probably have to lead the way.)
