### ISSUE TITLE
can't install in composer by version match conflict

### ISSUE THREAD

**Issue by danny007in** [PHPCSStandards/PHPCSExtra#87]
```console
PS C:\wamp64\www\Project> composer require --dev phpcsstandards/phpcsextra:"^1.0"


  [InvalidArgumentException]
  Could not find package phpcsstandards/phpcsextra in a version matching 1.0


require [--dev] [--dry-run] [--prefer-source] [--prefer-dist] [--fixed] [--no-suggest] [--no-progress] [--no-update] [--no-install] [--no-scripts] [--update-no-dev] [-w|--update-with-dependencies] [-W|--update-with-all-dependencies] [--with-dependencies] [--with-all-dependencies] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix 
APCU-AUTOLOADER-PREFIX] [--] [<packages>]...
```

**Comment by jrfnl** [comment]
@danny007in If you're looking for the DisallowLonelyIf sniff you'll need `dev-develop` for now as that's not yet in a release.

The 1.0.0 version is expected (hopefully) to be released soon. In the mean time, you can either use `dev-stable`, `dev-develop` or `^1.0` with `minimum-stability` in your `composer.json` set to `dev` or `alpha`.

See: https://getcomposer.org/doc/04-schema.md#minimum-stability

Does that help ?

**Comment by jrfnl** [comment]
Hi @danny007in Just checking if my answer above helped you get things running....

**Comment by danny007in** [comment]
> Hi @danny007in Just checking if my answer above helped you get things running....

Before urs answer
 I was directly installed exact version
Thanks

**Comment by jrfnl** [comment]
@danny007in Sorry, I'm not sure I understand your reply, but does this mean the issue is solved ? In that case, I think we can close the ticket ?
